import * as fs from 'fs';
import * as path from 'path';
import { EnvSchema, SchemaField } from './schema';

export type ExportFormat = 'docker-env' | 'kubernetes' | 'docker-compose' | 'shell';

export class Exporter {
  /**
   * Export schema to target format
   */
  static export(schema: EnvSchema, format: ExportFormat): string {
    switch (format) {
      case 'docker-env':
        return this.toDockerEnv(schema);
      case 'kubernetes':
        return this.toKubernetesConfigMap(schema);
      case 'docker-compose':
        return this.toDockerCompose(schema);
      case 'shell':
        return this.toShellExport(schema);
      default:
        throw new Error(`Unknown export format: ${format}`);
    }
  }

  /**
   * Generate Docker --env-file format
   * KEY=VALUE with defaults, skips required vars without defaults
   */
  private static toDockerEnv(schema: EnvSchema): string {
    const lines: string[] = ['# Generated by dotenv-schema', `# Generated at: ${new Date().toISOString()}`, ''];

    for (const [key, field] of Object.entries(schema)) {
      if (field.description) {
        lines.push(`# ${field.description}`);
      }
      if (field.default !== undefined) {
        const value = String(field.default);
        // Escape newlines for Docker env format
        const escapedValue = value.replace(/\n/g, '\\n');
        lines.push(`${key}=${escapedValue}`);
      } else if (!field.required) {
        lines.push(`# ${key}=`);
      } else {
        lines.push(`# ${key}=<required - no default>`);
      }
      lines.push('');
    }

    return lines.join('\n');
  }

  /**
   * Generate Kubernetes ConfigMap YAML
   */
  private static toKubernetesConfigMap(schema: EnvSchema): string {
    const lines: string[] = [
      '# Generated by dotenv-schema',
      `# Generated at: ${new Date().toISOString()}`,
      'apiVersion: v1',
      'kind: ConfigMap',
      'metadata:',
      '  name: app-env',
      'data:',
    ];

    for (const [key, field] of Object.entries(schema)) {
      const value = field.default !== undefined ? String(field.default) : '';
      if (field.description) {
        lines.push(`    # ${field.description}`);
      }
      
      // Use YAML block scalar for multiline values, quoted string for simple values
      if (value.includes('\n')) {
        // Multiline values - use block literal scalar (content on next line)
        const contentLines = value.split('\n');
        lines.push(`    ${key}: |-`);
        for (const contentLine of contentLines) {
          lines.push(`      ${contentLine}`);
        }
      } else if (value.includes(':') || value.includes('#') || value.includes('{') || value.includes('[') || value.includes('!') || value.includes('"') || value.includes("'") || value.includes('&') || value.includes('*') || value.includes('?') || value.includes('|') || value.includes('>') || value.includes('%') || value.includes('@') || value.includes('`') || value.includes(',')) {
        // Complex values - use double-quoted string with proper YAML escaping
        const escapedValue = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\t/g, '\\t');
        lines.push(`    ${key}: "${escapedValue}"`);
      } else {
        // Simple values - use quoted string for safety
        const escapedValue = value.replace(/"/g, '\\"');
        lines.push(`    ${key}: "${escapedValue}"`);
      }
    }

    lines.push('');
    return lines.join('\n');
  }

  /**
   * Generate docker-compose env_file style .env
   */
  private static toDockerCompose(schema: EnvSchema): string {
    const lines: string[] = ['# docker-compose environment file', '# Generated by dotenv-schema', ''];

    for (const [key, field] of Object.entries(schema)) {
      const comment = field.description ? ` # ${field.description}` : '';
      const tags: string[] = [];
      if (field.required && field.default === undefined) tags.push('REQUIRED');
      else if (!field.required) tags.push('optional');
      if (field.type !== 'string') tags.push(`type: ${field.type}`);

      const tagStr = tags.length > 0 ? ` [${tags.join(', ')}]` : '';

      if (field.default !== undefined) {
        const rawValue = String(field.default);
        // Quote values containing special characters
        const needsQuote = rawValue.includes('#') || rawValue.includes(' ') || rawValue.includes('=') || rawValue.includes('\n') || rawValue.includes("'") || rawValue.includes('"');
        const escapedValue = needsQuote ? `"${rawValue.replace(/"/g, '\\"')}"` : rawValue;
        lines.push(`${key}=${escapedValue}${tagStr}${comment}`);
      } else if (field.required) {
        lines.push(`${key}=<FILL ME>${tagStr}${comment}`);
      } else {
        lines.push(`# ${key}=${tagStr}${comment}`);
      }
    }

    lines.push('');
    return lines.join('\n');
  }

  /**
   * Generate shell export statements
   */
  private static toShellExport(schema: EnvSchema): string {
    const lines: string[] = ['#!/bin/bash', '# Generated by dotenv-schema', ''];

    for (const [key, field] of Object.entries(schema)) {
      if (field.description) {
        lines.push(`# ${field.description}`);
      }
      if (field.default !== undefined) {
        const value = String(field.default);
        
        if (value.includes('\n')) {
          // Multiline values use ANSI-C quoting - simplified approach
          const escaped = value.replace(/\\/g, '\\\\').replace(/'/g, "'\\''").replace(/"/g, '\\"').replace(/\n/g, '\\n');
          lines.push(`export ${key}=$'${escaped}'`);
        } else {
          // Simple values use regular quoting
          const escaped = value.replace(/'/g, "'\\''");
          lines.push(`export ${key}='${escaped}'`);
        }
      } else if (field.required) {
        lines.push(`export ${key}='<REQUIRED - set this value>'`);
      } else {
        lines.push(`# export ${key}=''`);
      }
      lines.push('');
    }

    return lines.join('\n');
  }

  /**
   * Write exported content to file
   */
  static writeToFile(content: string, filePath: string): void {
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(filePath, content, 'utf-8');
  }
}